name: Deploy django to develop stage

on:
  push:
    branches:
      - develop
      - Issue-*
    paths:
      - .github/workflows/deploy-dev-django.yml
      - django/Dockerfile
      - django/Pipfile.lock
      - django/ecs/dev/django-task-definition.json
      - django/src/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./django
      GITHUB_CONTAINER_IMAGE: docker.pkg.github.com/${{ github.repository }}/django:dev
      REMOTE_CONTAINER_NAME: ghilbut/byfs

    steps:
      - run: curl -v -XDELETE https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@docker.pkg.github.com/v2/${{ github.repository }}/django/manifests/dev

      - uses: actions/checkout@v2

      - name: Build the tagged Docker image
        run: |
          docker build \
                 -t ${GITHUB_CONTAINER_IMAGE} \
                 --label GITHUB_REF=${GITHUB_REF} \
                 --label GITHUB_SHA=${GITHUB_SHA} \
                 .
        working-directory: ${{ env.WORKDIR }}

      - name: Login to push to github packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      - name: Push docker image to github packages
        run: docker push ${GITHUB_CONTAINER_IMAGE}

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTAINER_IMAGE: docker.pkg.github.com/${{ github.repository }}/django:dev
      REMOTE_CONTAINER_NAME: ghilbut/byfs

    steps:
      - uses: actions/checkout@v2

      - name: Login to pull from github packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      - name: Pull docker image from github packages
        run: docker pull ${GITHUB_CONTAINER_IMAGE}

      - id: docker
        name: Make docker image tag to publish to docker hub
        run: echo ::set-output name=image::${REMOTE_CONTAINER_NAME}:dev-$(date +'%Y.%m.%d-%H.%M.%S')

      - name: Tag with timestamp to current Docker image
        run: docker image tag ${GITHUB_CONTAINER_IMAGE} ${{ steps.docker.outputs.image }}
      - name: Tag the latest to current Docker image
        run: docker image tag ${GITHUB_CONTAINER_IMAGE} ${REMOTE_CONTAINER_NAME}:latest

      - name: Login to push to docker-hub registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push the tagged Docker image
        run: docker push ${{ steps.docker.outputs.image }}
      - name: Push the latest Docker image
        run: docker push ${REMOTE_CONTAINER_NAME}:latest

      - name: Checkout
        run: docker pull ${{ steps.docker.outputs.image }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BYFS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BYFS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.BYFS_AWS_REGION }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: django/ecs/dev/django-task-definition.json
          container-name: django
          image: ${{ steps.docker.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: byfs-dev-django
          cluster: byfs
          wait-for-service-stability: true

      - id: Login AWS ECR
        name: Login to Amazon ECR 
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push image to AWS ECR
        run: |
          docker image tag ${GITHUB_CONTAINER_IMAGE} ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest && \
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: byfs

      - name: Logout AWS ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}


  #clean:
  #  needs:
  #    - build
  #    - deploy
  #  if: always()
  #  runs-on: ubuntu-latest
  #  env:
  #    GITHUB_CONTAINER_IMAGE: docker.pkg.github.com/${{ github.repository }}/django:dev

  #  steps:
  #    - name: Login to pull from github packages
  #      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
  #    - name: Pull docker image from github packages
  #      run: docker pull ${GITHUB_CONTAINER_IMAGE}


