name: Deploy api backtend to develop stage

on:
  push:
    branches:
      - develop
      - Issue-*
    paths:
      - .github/workflows/deploy-dev-django.yml
      - django/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BYFS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BYFS_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.BYFS_AWS_REGION }}

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: django/ecs/dev/task-definition.json
        container-name: django
        image: ghilbut/byfs:latest

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: byfs-dev-django
        cluster: byfs
        wait-for-service-stability: true
